"""add password_hash to users

Revision ID: a9327a283123
Revises: 0bad12f9d217
Create Date: 2026-08-06 20:31:47.592059

Adding a NOT NULL column to a table that already has rows is the classic
migration trap. Alembic's autogenerated version was:

    op.add_column('users',
        sa.Column('password_hash', sa.String(255), nullable=False))

which fails the moment `users` is non-empty, because Postgres has no value to
put in the existing rows and the column forbids NULL. It passes on an empty
development database and then breaks on production, which is the worst
possible place to find out.

The fix is to split it into three steps: add the column permissive, fill it,
then tighten the constraint.

The interesting question is what to fill it with. These accounts predate
passwords, so there is no correct value -- only safe and unsafe ones. The
tempting shortcuts are both wrong:

  - A known placeholder like hash("changeme") hands an attacker a working
    password for every legacy account.
  - An empty string is not a valid bcrypt hash, so bcrypt.checkpw raises
    ValueError("Invalid salt") instead of returning False. That turns a login
    attempt into a 500, and an endpoint that crashes on a specific account is
    itself an information leak.

So each row is backfilled with a *real* bcrypt hash of freshly generated
random bytes that are never recorded anywhere. The hash is structurally valid,
so verify_password compares against it normally and simply always returns
False. The account is unreachable by any password, including by whoever wrote
this migration.

The honest consequence: those users are locked out permanently, because
password reset is out of scope for QJ-2. In this repository the only affected
row is the fixture created by scripts/seed.py, so the cost is nil. On a real
system this step would be paired with a reset flow.
"""

import secrets
from collections.abc import Sequence
from typing import Union

import bcrypt
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9327a283123"
down_revision: str | Sequence[str] | None = "0bad12f9d217"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: add the column permissively so existing rows survive.
    op.add_column(
        "users", sa.Column("password_hash", sa.String(length=255), nullable=True)
    )

    # Step 2: give every existing row an unusable credential.
    #
    # Hashed per row rather than once for the whole table. One shared hash
    # would work, since the plaintext is discarded either way, but identical
    # hashes across rows advertise "these accounts share a password" to anyone
    # reading a dump -- the same property salting exists to destroy. Cheap to
    # avoid, so avoid it.
    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT id FROM users WHERE password_hash IS NULL"))
    for (user_id,) in rows.fetchall():
        unusable = bcrypt.hashpw(
            secrets.token_urlsafe(32).encode("utf-8"), bcrypt.gensalt()
        ).decode("utf-8")
        bind.execute(
            sa.text("UPDATE users SET password_hash = :h WHERE id = :id"),
            {"h": unusable, "id": user_id},
        )

    # Step 3: now that no NULLs remain, enforce the constraint.
    op.alter_column("users", "password_hash", nullable=False)

    # Registration collects email and password only, so a display name is no
    # longer available at signup. Widening NOT NULL -> NULL is always safe:
    # every existing value still satisfies the looser constraint.
    op.alter_column(
        "users",
        "display_name",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Narrowing NULL -> NOT NULL is the dangerous direction, and it fails on
    # any row this migration's upgrade allowed to be NULL. Backfill first,
    # using the email local-part, which is the closest thing to a display name
    # we can reconstruct without inventing data.
    op.execute(
        sa.text(
            "UPDATE users SET display_name = split_part(email, '@', 1) "
            "WHERE display_name IS NULL"
        )
    )
    op.alter_column(
        "users",
        "display_name",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )

    # Dropping password_hash destroys every credential in the table. Rolling
    # this back means every user must re-register; there is no path that
    # recovers the hashes once the column is gone.
    op.drop_column("users", "password_hash")
